name:                memento-mori
version:             0.2.0.0
github:              "maxthomas/memento-mori"
license:             BSD3
author:              "max"
maintainer:          "max@maxthomas.io"
copyright:           "Copyright Max Thomas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Library and application related to days lived and accurate ages (fractions of year instead of integers).
category:            Utility, Learning Haskell

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/maxthomas/memento-mori#readme>

dependencies:
- base >= 4.7 && < 5
- time

library:
  source-dirs: src

executables:
  memento-mori:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - memento-mori

tests:
  memento-mori-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - memento-mori
